name: Build and deploy JAR app to Azure Web App

env:
  AZURE_WEBAPP_NAME: AxelJavaSpringApp
  JAVA_VERSION: '11'
  DISTRIBUTION: zulu
  RESOURCE_GROUP: AxelJavaSpringApp_group

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B6D801B815834431834CF9E2D42598DB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_55B9464E72AB4B7A9185B2B95F09A8A2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DD1BBF5E684D41F7A0BEEF0FA9F11F08 }}

      - name: Install Azure CLI (if needed)
        run: |
          if ! command -v az &> /dev/null; then
            echo "Installing Azure CLI..."
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App using Azure CLI
        run: |
          jar_file=$(find . -name "*.jar" | head -n 1)
          echo "Deploying $jar_file to Azure Web App..."
          az webapp deploy \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --src-path "$jar_file" \
            --type jar

