name: Build and deploy JAR app to Azure Web App

env:
  AZURE_WEBAPP_NAME: AxelJavaSpringApp             # Replace with your Azure Web App name
  JAVA_VERSION: '17'
  DISTRIBUTION: zulu
  RESOURCE_GROUP: AxelJavaSpringApp_group          # Replace with your Azure Resource Group

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App using Azure CLI
        run: |
          jar_file=$(find . -name "*.jar" | head -n 1)
          echo "Deploying $jar_file to Azure Web App..."
          az webapp deploy \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --src-path "$jar_file" \
            --type jar
