name: Build and deploy JAR app to Azure Web App - AxelJavaSpringApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ----------------------
  # 1️⃣ BUILD JOB
  # ----------------------
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
